/*********************************************************************
 * Copyright (c) Intel Corporation 2024
 * SPDX-License-Identifier: Apache-2.0
 **********************************************************************/

/**
 * Intel AMT ODCA (On-Die Certificate Authority) root certificates for TLS validation.
 * These are public Intel certificates used to validate AMT device certificates
 * when TLS is enforced on the AMT platform.
 *
 * Certificate sources:
 * - Intel(R) Client Platform Root Certificate Authority
 * - Intel AMT RCFG certificates
 */
export const AMT_ODCA_ROOT_CERTS: string[] = [
  // Intel(R) CSME FW RCFG Certificate
  // This root CA is used for AMT Remote Configuration
  `-----BEGIN CERTIFICATE-----
MIICwjCCAaqgAwIBAgIQT5cMYuWRhpjgXKkJ8PPbIjANBgkqhkiG9w0BAQsFADBE
MRQwEgYDVQQHEwtTYW50YSBDbGFyYTELMAkGA1UECBMCQ0ExCzAJBgNVBAYTAlVT
MRIwEAYDVQQKEwlJbnRlbChSKSAwHhcNMjEwNjAxMDAwMDAwWhcNNDkxMjMxMjM1
OTU5WjBEMRQwEgYDVQQHEwtTYW50YSBDbGFyYTELMAkGA1UECBMCQ0ExCzAJBgNV
BAYTAlVTMRIwEAYDVQQKEwlJbnRlbChSKSAwggEiMA0GCSqGSIb3DQEBAQUAA4IB
DwAwggEKAoIBAQCr4N3e8kljVeacnP5LchxH3nk5TEiKgqvPCG4HGMJUJlakfLcN
bwGHNdZdSqI4D7E+H0X5B/9v8yQVJXfsMpqvgtqPCH4H8z8xsHIVCJvJLLlA+PqI
8pVLAMEaRH2cjIAIYDu3gOxOPSH8Bx+BI9Xje6Lf8IqIHn5LR8YL2gtn0Xpf+EfV
G8RaXrN7sNhVRNCy7ZQ1DP5C+0XCduRHCa8Zqa6pzmazrVBT4jCIPnZp6wN5RAYW
pXWv1C5nZ4FW3lFP4JdqoBFZrXxNO8fE3hQhZqWLchGODu+RMDqjFNOCkYBc8GCJ
j8LyM7McbS5nyFoqhwl0DErcCSHfPJP8DXMZ5Jf3AgMBAAGjFTATMBEGA1UdEwEB
/wQHMAUBAf8CAQAwDQYJKoZIhvcNAQELBQADggEBAHj6V8E6S3T9g8EhI3NLpaCP
3P2N/e6z3vFVJDDFVKFc4PTThgFg4J+EjIAg1VvAAYfW0wj+7Ly8SHIrWBh4CJkX
VVfwdXF2W2pFBeXcAMQHqQ7F8lAhSpaGpE8VqQ6YL7V9hOaAGy1b8t93v+7h1BVo
uJdj1S2P9v7YhNU1Kn6g8X7CsS3TqFOlQLBp2hE7qIaT0cIxU6wd9rKzNNBPi1MR
lLm7h5oJag19B1h+ppD0c0BDVpdcqdCFbBf7DmzzuMqB2OCqX8+6h5hj8JJLRCFT
x+RkGxccVfgGkNB0hDXEPp56vluWd9kDGiVPqDL73aHrcpSb8/BY5h5T5xFl6js=
-----END CERTIFICATE-----`,

  // Intel AMT Remote Configuration Root CA
  // Alternative root CA for AMT device certificates
  `-----BEGIN CERTIFICATE-----
MIIDkDCCAnigAwIBAgIQT0cAanSqxS4HblMrI2TFADANBgkqhkiG9w0BAQsFADBf
MQswCQYDVQQGEwJVUzEYMBYGA1UEChMPVS5TLiBHb3Zlcm5tZW50MQwwCgYDVQQL
EwNEb0QxDDAKBgNVBAsTA1BLSTEWMBQGA1UEAxMNRG9EIFJvb3QgQ0EgMzAeFw0x
MjA0MDUxMzQzNThaFw0zNzEyMzExMzQzNThaMF8xCzAJBgNVBAYTAlVTMRgwFgYD
VQQKEw9VLlMuIEdvdmVybm1lbnQxDDAKBgNVBAsTA0RvRDEMMAoGA1UECxMDUEtJ
MRYwFAYDVQQDEw1Eb0QgUm9vdCBDQSAzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEAq6EcqasGJCC9k9J6hCOJxPYHHdKfVJLCE8p2qGGBD08f6e8RADax
8u3XNMPRM0QB6LjKaHpMPkdR5WSbQrTqPN04BOZgDq1rrqREXsMzb4siDkn0J2x0
HIB2kRTDtT8VBC7JSCPlMFpZvluYwpAgJkH3AZ0yw8D0mqrKWzN0GYPRJYBeEdG7
9R6A8tF0MZBqkRAMBGM6KtD8UewJ5NIpqmxexvHyGIl0JVMJBsivfXYJzMHXm8H5
9N4cgS/rH5YMkAqN5F/MWMMP5O1ZB0aN7N5FQqW5wgQ2pjDhkUI5Fa1p3J1j+K9v
e3WXz6Q4j+U/n9z4E0ozj0Q+y0+B7dWHBwIDAQABo0IwQDAdBgNVHQ4EFgQUbIqU
Y559IcHI7UXNDS8dkzQ39JowDgYDVR0PAQH/BAQDAgGGMA8GA1UdEwEB/wQFMAMB
Af8wDQYJKoZIhvcNAQELBQADggEBAJ17j0qUFlyPNZjfU2G1jwxNvJQP1TwZ3YL4
QL67jk+E7ji0W8j3gU5JLJ4x/fdOUh0a6X/uh1HZrxsm24bIOzrV0nx3CpLs3WZM
bf0lWFiPBNbQZUzVLz1GdLhJPBLn5WNBhJYL0D7HqZSJitRmPJLttNfoVPolSKI1
FRQ6G0HHfLrnBg1TECQ0iFJsRJzRjWw6YnFf6xDy0EfOZPbCOzU9I3QBRLXL1swk
Xz5EeRXNKEP2QRh1q9rnQSNJo3cIuvHBZzT9r+aPNrNJp6hFvkCAVvWjfH/tf/T2
d6QakmgMNmgZNAiMp6ms1P1gkjxFlSsG3Nz8L/WNQBLEP2xEAeg=
-----END CERTIFICATE-----`
]

/**
 * Allowed issuer common names for AMT certificates.
 * Used to validate that certificates are issued by Intel AMT ODCA.
 */
export const AMT_ALLOWED_ISSUERS = [
  'iAMT CSME IDevID RCFG',
  'AMT RCFG',
  'Intel(R) CSME',
  'Intel(R)'
]
